.PHONY: help install dev-install lint test cover run worker migrate revision \
        docker-build up down logs ps

help:
	@echo "Targets:"
	@echo "  install       install runtime deps"
	@echo "  dev-install   install runtime + dev deps"
	@echo "  lint          ruff check"
	@echo "  test          run pytest"
	@echo "  cover         run pytest with coverage"
	@echo "  run           run the web app locally (waitress/flask)"
	@echo "  worker        run an RQ worker locally"
	@echo "  migrate       alembic upgrade head"
	@echo "  revision m=.. create an autogenerated migration"
	@echo "  up/down/logs  docker compose lifecycle"

install:
	pip install .

dev-install:
	pip install -e ".[dev,mcp,langchain]"

lint:
	ruff check app research_agent tests wsgi.py config.py main.py mcp_server.py

test:
	pytest -q

cover:
	pytest --cov=app --cov=research_agent --cov-report=term-missing

run:
	python -m app.cli init-db || true
	python web.py

worker:
	python -m app.jobs.worker

migrate:
	alembic upgrade head

revision:
	alembic revision --autogenerate -m "$(m)"

docker-build:
	docker compose build

up:
	docker compose up -d --build

down:
	docker compose down

logs:
	docker compose logs -f --tail=100

ps:
	docker compose ps
